FROM debian:bookworm-slim

ARG TARGETARCH

RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

COPY binaries/${TARGETARCH}/tb /usr/local/bin/tb

RUN mkdir -p /root/.taskbook

WORKDIR /root

CMD ["bash"]
